cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.Detalle.as_view(), name="cart_detail"),
    url(r'^add/(?P<producto_id>\d+)/$', views.Agregar.as_view(), name="cart_add"),
    url(r'^remove/(?P<producto_id>\d+)/$', views.Remove.as_view(), name="cart_remove")
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.Home.as_view(), name="home"),
]

soporte/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from tienda import urls as tiendaUrls
from cart import urls as cartUrls
from accounts import urls as accUrls
from django.conf import settings
from orders import urls as orderUrls
from paypal.standard.ipn import urls as paypalUrls
from payment import urls as paymentUrls
from main import urls as UrlsMain
#for socialauth
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

SOCIAL_AUTH_URL_NAMESPACE = 'social'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include(UrlsMain,namespace="home")),
    url(r'^tienda/', include(tiendaUrls, namespace="tienda")),
    url(r'^cart/', include(cartUrls, namespace="cart")),
    url(r'^accounts/', include(accUrls, namespace="accounts")),
    url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs ={'document_root':settings.MEDIA_ROOT}
        ),

    url(r'^orders/', include(orderUrls, namespace="orders")),
    url(r'^paypal/', include(paypalUrls)),
    url(r'^payment/', include(paymentUrls,namespace='payment')),

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    #url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    # Logout URL
    url(
        r'^users/logout/$',
        logout,
        {'next_page': '/products'},
        name="user-logout"),
]

tienda/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$', views.Lista.as_view(), name="tienda"),
    url(r'^(?P<producto_id>\d+)/$', views.Detalle.as_view(), name="detalle"),
]

main/views.py
from django.shortcuts import render
from django.views.generic import View

class Home(View):
	def get(self, request):
		template_name= 'home.html'
		return render(request, template_name)

main/templates/base.html
{%load static%}

<html>

<head>
	<title>
		{%block titulo%} Soporte Técnico 24hrs {%endblock titulo%}
	</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!--Import Google Icon Font-->
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
	<!--Import Google Icon Font-->
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<!--Import materialize.css-->
	<link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />

	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" /> {%block head%} {%endblock head%}
</head>

<body>

	<!--Import jQuery before materialize.js-->
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script type="text/javascript" src="js/materialize.min.js"></script>

	<nav class="blue darken-4 navbar-fixed">

		<div class="nav-wrapper">
			<a href="{%url 'home:home'%}" class="brand-logo">Total Service</a>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
				<li><a href="{%url 'home:home'%}">Inicio</a></li>
				<li><a href="#">Acerca</a></li>
				<li><a href="">Iniciar Sesión</a></li>
				<li><a href="">Registrate</a></li>
				<li><a href="{%url 'tienda:tienda'%}">Tienda</a></li>
				<li><a href="{%url 'cart:cart_detail'%}">
				{%with total_items=cart|length%}<img src="/media/tienda/carrito.png {{producto.imagen}}" height="20">
				{{total_items}} {%if total_items > 0%}
			 	{{total_items|pluralize}}
			  {%else%} {{tota_items}} {%endif%}{%endwith%}</a></li>
			</ul>
		</div>
	</nav>

	{%block content%}
	<nav class="black darken-4">
		<ul id="nav-mobile" class="center hide-on-med-and-dow">
			<li><a>Soporte las 24 horas</a></li>
			<ul id="nav-mobile" class="right hide-on-med-and-dow">
				<li><a>Llamanos 7711548189</a></li>
			</ul>
	</nav>
	<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
		<a class="btn-floating btn-large red">
			<i class="large material-icons">mode_edit</i>
		</a>
		<ul>
			<li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
			<li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
			<li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
			<li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
		</ul>
	</div>

	{%endblock content%}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
	 {%block scripts%} 
	 
	 {%endblock scripts%}
</body>

</html>

main/templates/home.html
{% extends 'base.html'%} 
{% block content%}



	<div class="slider fullscreen">
	    <ul class="slides">
	      <li>
		        <img src="/media/tienda/slider/s1.jpg"> <!-- random image -->
		        <div class="caption left-align">
			          <h2 class="black-text">¡Aprende!</h2>
			          <h5 class="black-text">¡Desarrolla tus skills como developer!</h5>
		        </div>
	      </li>
	      <li>
		        <img src="/media/tienda/slider/s1.jpg"> <!-- random image -->
		        <div class="caption left-align">
			          <h2 class="white-text">¡Crear!</h2>
			          <h5 class="white-text">Es lo de hoy</h5>
		        </div>
		  </li>
		  <li>
			   	 <img src="/media/tienda/slider/st.jpg"> <!-- random image -->
		      	 <div class="caption left-align">
			          <h2 class="black-text">¡Trabaja en equipo!</h2>
			          <h5 class="black-text">Comparte conocimientos</h5>
		        </div>
		  </li>
   		</ul>
	</div>			



{%endblock content%}
{%block scripts%}
	<script>
		$(document).ready(function(){
    		$('.slider').slider({full_width: true, indicators:true});

		});
	</script>
{%endblock scripts%}